[package]
name = "redstone"
version = "0.1.0"
authors = ["Ryan Liang <rl@ryanl.io>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[profile.release]
lto         = true
panic       = 'abort'
opt-level   = 3

[package.metadata.cargo-xbuild]
memcpy = false
panic_immediate_abort = true
